
namespace iFruitAddon
{
    public sealed class ContactIcon : PhoneImage
    {
        /// <summary>
        /// Initialize the class.
        /// </summary>
        /// <param name="txd"></param>
        public ContactIcon(string txd) : base(txd)
        { }

        // Full list:
        // https://wiki.gtanet.work/index.php?title=Notification_Pictures
        //
        public static ContactIcon Generic { get { return new ContactIcon("char_default"); } }
        public static ContactIcon Abigail { get { return new ContactIcon("char_abigail"); } }
        public static ContactIcon AllCharacters { get { return new ContactIcon("char_all_players_conf"); } }
        public static ContactIcon Amanda { get { return new ContactIcon("char_amanda"); } }
        public static ContactIcon Ammunation { get { return new ContactIcon("char_ammunation"); } }
        public static ContactIcon Andreas { get { return new ContactIcon("char_andreas"); } }
        public static ContactIcon Antonia { get { return new ContactIcon("char_antonia"); } }
        public static ContactIcon Arthur { get { return new ContactIcon("char_arthur"); } }
        public static ContactIcon Ashley { get { return new ContactIcon("char_ashley"); } }
        public static ContactIcon BankOfLiberty { get { return new ContactIcon("char_bank_bol"); } }
        public static ContactIcon FleecaBank { get { return new ContactIcon("char_bank_fleeca"); } }
        public static ContactIcon MazeBank { get { return new ContactIcon("char_bank_maze"); } }
        public static ContactIcon Barry { get { return new ContactIcon("char_barry"); } }
        public static ContactIcon Beverly { get { return new ContactIcon("char_beverly"); } }
        public static ContactIcon Bikesite { get { return new ContactIcon("char_bikesite"); } }
        public static ContactIcon Blank { get { return new ContactIcon("char_blank_entry"); } }
        public static ContactIcon Blimp { get { return new ContactIcon("char_blimp"); } }
        public static ContactIcon Blocked { get { return new ContactIcon("char_blocked"); } }
        public static ContactIcon Boatsite { get { return new ContactIcon("char_boatsite"); } }
        public static ContactIcon BrokenDownGirl { get { return new ContactIcon("char_broken_down_girl"); } }
        public static ContactIcon Bugstars { get { return new ContactIcon("char_bugstars"); } }
        public static ContactIcon Emergency { get { return new ContactIcon("char_call911"); } }
        public static ContactIcon LegendaryMotorsport { get { return new ContactIcon("char_carsite"); } }
        public static ContactIcon SSASuperAutos { get { return new ContactIcon("char_carsite2"); } }
        public static ContactIcon Castro { get { return new ContactIcon("char_castro"); } }
        public static ContactIcon ChatIcon { get { return new ContactIcon("char_chat_call"); } }
        public static ContactIcon Chef { get { return new ContactIcon("char_chef"); } }
        public static ContactIcon Cheng { get { return new ContactIcon("char_cheng"); } }
        public static ContactIcon ChengSr { get { return new ContactIcon("char_chengsr"); } }
        public static ContactIcon Chop { get { return new ContactIcon("char_chop"); } }
        public static ContactIcon CreatorPortraits { get { return new ContactIcon("char_creator_portraits"); } }
        public static ContactIcon Cris { get { return new ContactIcon("char_cris"); } }
        public static ContactIcon Dave { get { return new ContactIcon("char_dave"); } }
        public static ContactIcon Denise { get { return new ContactIcon("char_denise"); } }
        public static ContactIcon DetonateBomb { get { return new ContactIcon("char_detonatebomb"); } }
        public static ContactIcon DetonatePhone { get { return new ContactIcon("char_detonatephone"); } }
        public static ContactIcon Devin { get { return new ContactIcon("char_devin"); } }
        public static ContactIcon DialASub { get { return new ContactIcon("char_dial_a_sub"); } }
        public static ContactIcon Dom { get { return new ContactIcon("char_dom"); } }
        public static ContactIcon DomesticGirl { get { return new ContactIcon("char_domestic_girl"); } }
        public static ContactIcon Dreyfuss { get { return new ContactIcon("char_dreyfuss"); } }
        public static ContactIcon DrFriedlander { get { return new ContactIcon("char_dr_friedlander"); } }
        public static ContactIcon Epsilon { get { return new ContactIcon("char_epsilon"); } }
        public static ContactIcon EstateAgent { get { return new ContactIcon("char_estate_agent"); } }
        public static ContactIcon Facebook { get { return new ContactIcon("char_facebook"); } }
        public static ContactIcon Filmnoir { get { return new ContactIcon("char_filmnoir"); } }
        public static ContactIcon Floyd { get { return new ContactIcon("char_floyd"); } }
        public static ContactIcon Franklin { get { return new ContactIcon("char_franklin"); } }
        public static ContactIcon FranklinTrevor { get { return new ContactIcon("char_frank_trev_conf"); } }
        public static ContactIcon GayMilitary { get { return new ContactIcon("char_gaymilitary"); } }
        public static ContactIcon Hao { get { return new ContactIcon("char_hao"); } }
        public static ContactIcon HitcherGirl { get { return new ContactIcon("char_hitcher_girl"); } }
        public static ContactIcon Human { get { return new ContactIcon("char_humandefault"); } }
        public static ContactIcon Hunter { get { return new ContactIcon("char_hunter"); } }
        public static ContactIcon Jimmy { get { return new ContactIcon("char_jimmy"); } }
        public static ContactIcon JimmyBoston { get { return new ContactIcon("char_jimmy_boston"); } }
        public static ContactIcon Joe { get { return new ContactIcon("char_joe"); } }
        public static ContactIcon Josef { get { return new ContactIcon("char_josef"); } }
        public static ContactIcon Josh { get { return new ContactIcon("char_josh"); } }
        public static ContactIcon Lamar { get { return new ContactIcon("char_lamar"); } }
        public static ContactIcon Lazlow { get { return new ContactIcon("char_lazlow"); } }
        public static ContactIcon Lester { get { return new ContactIcon("char_lester"); } }
        public static ContactIcon Skull { get { return new ContactIcon("char_lester_deathwish"); } }
        public static ContactIcon LesterFranklin { get { return new ContactIcon("char_lest_frank_conf"); } }
        public static ContactIcon LesterMichael { get { return new ContactIcon("char_lest_mike_conf"); } }
        public static ContactIcon Lifeinvader { get { return new ContactIcon("char_lifeinvader"); } }
        public static ContactIcon LSCustoms { get { return new ContactIcon("char_ls_customs"); } }
        public static ContactIcon LSTouristBoard { get { return new ContactIcon("char_ls_tourist_board"); } }
        public static ContactIcon Manuel { get { return new ContactIcon("char_manuel"); } }
        public static ContactIcon Marnie { get { return new ContactIcon("char_marnie"); } }
        public static ContactIcon Martin { get { return new ContactIcon("char_martin"); } }
        public static ContactIcon MaryAnn { get { return new ContactIcon("char_mary_ann"); } }
        public static ContactIcon Maude { get { return new ContactIcon("char_maude"); } }
        public static ContactIcon Mechanic { get { return new ContactIcon("char_mechanic"); } }
        public static ContactIcon Michael { get { return new ContactIcon("char_michael"); } }
        public static ContactIcon MichaelFranklin { get { return new ContactIcon("char_mike_frank_conf"); } }
        public static ContactIcon MichaelTrevor { get { return new ContactIcon("char_mike_trev_conf"); } }
        public static ContactIcon Milsite { get { return new ContactIcon("char_milsite"); } }
        public static ContactIcon Minotaur { get { return new ContactIcon("char_minotaur"); } }
        public static ContactIcon Molly { get { return new ContactIcon("char_molly"); } }
        public static ContactIcon MP_ArmyContact { get { return new ContactIcon("char_mp_army_contact"); } }
        public static ContactIcon MP_BikerBoss { get { return new ContactIcon("char_mp_biker_boss"); } }
        public static ContactIcon MP_BikerMechanic { get { return new ContactIcon("char_mp_biker_mechanic"); } }
        public static ContactIcon MP_Brucie { get { return new ContactIcon("char_mp_brucie"); } }
        public static ContactIcon MP_Detonatephone { get { return new ContactIcon("char_mp_detonatephone"); } }
        public static ContactIcon MP_FamBoss { get { return new ContactIcon("char_mp_fam_boss"); } }
        public static ContactIcon MP_FibContact { get { return new ContactIcon("char_mp_fib_contact"); } }
        public static ContactIcon MP_FmContact { get { return new ContactIcon("char_mp_fm_contact"); } }
        public static ContactIcon MP_Gerald { get { return new ContactIcon("char_mp_gerald"); } }
        public static ContactIcon MP_Julio { get { return new ContactIcon("char_mp_julio"); } }
        public static ContactIcon MP_Mechanic { get { return new ContactIcon("char_mp_mechanic"); } }
        public static ContactIcon MP_Merryweather { get { return new ContactIcon("char_mp_merryweather"); } }
        public static ContactIcon MP_MexBoss { get { return new ContactIcon("char_mp_mex_boss"); } }
        public static ContactIcon MP_MexDocks { get { return new ContactIcon("char_mp_mex_docks"); } }
        public static ContactIcon MP_MexLt { get { return new ContactIcon("char_mp_mex_lt"); } }
        public static ContactIcon MP_MorsMutual { get { return new ContactIcon("char_mp_mors_mutual"); } }
        public static ContactIcon MP_ProfBoss { get { return new ContactIcon("char_mp_prof_boss"); } }
        public static ContactIcon MP_RayLavoy { get { return new ContactIcon("char_mp_ray_lavoy"); } }
        public static ContactIcon MP_Roberto { get { return new ContactIcon("char_mp_roberto"); } }
        public static ContactIcon MP_Snitch { get { return new ContactIcon("char_mp_snitch"); } }
        public static ContactIcon MP_Stretch { get { return new ContactIcon("char_mp_stretch"); } }
        public static ContactIcon MP_StripclubPr { get { return new ContactIcon("char_mp_stripclub_pr"); } }
        public static ContactIcon MrsThornhill { get { return new ContactIcon("char_mrs_thornhill"); } }
        public static ContactIcon Multiplayer { get { return new ContactIcon("char_multiplayer"); } }
        public static ContactIcon Nigel { get { return new ContactIcon("char_nigel"); } }
        public static ContactIcon Omega { get { return new ContactIcon("char_omega"); } }
        public static ContactIcon Oneil { get { return new ContactIcon("char_oneil"); } }
        public static ContactIcon Ortega { get { return new ContactIcon("char_ortega"); } }
        public static ContactIcon Oscar { get { return new ContactIcon("char_oscar"); } }
        public static ContactIcon Patricia { get { return new ContactIcon("char_patricia"); } }
        public static ContactIcon Pegasus { get { return new ContactIcon("char_pegasus_delivery"); } }
        public static ContactIcon Planesite { get { return new ContactIcon("char_planesite"); } }
        public static ContactIcon Property_ArmsTrafficking { get { return new ContactIcon("char_property_arms_trafficking"); } }
        public static ContactIcon Property_BarAirport { get { return new ContactIcon("char_property_bar_airport"); } }
        public static ContactIcon Property_BarBayview { get { return new ContactIcon("char_property_bar_bayview"); } }
        public static ContactIcon Property_BarCafeRojo { get { return new ContactIcon("char_property_bar_cafe_rojo"); } }
        public static ContactIcon Property_BarCockotoos { get { return new ContactIcon("char_property_bar_cockotoos"); } }
        public static ContactIcon Property_BarEclipse { get { return new ContactIcon("char_property_bar_eclipse"); } }
        public static ContactIcon Property_BarFes { get { return new ContactIcon("char_property_bar_fes"); } }
        public static ContactIcon Property_BarHenHouse { get { return new ContactIcon("char_property_bar_hen_house"); } }
        public static ContactIcon Property_BarHiMen { get { return new ContactIcon("char_property_bar_hi_men"); } }
        public static ContactIcon Property_BarHookies { get { return new ContactIcon("char_property_bar_hookies"); } }
        public static ContactIcon Property_BarIrish { get { return new ContactIcon("char_property_bar_irish"); } }
        public static ContactIcon Property_BarLesBianco { get { return new ContactIcon("char_property_bar_les_bianco"); } }
        public static ContactIcon Property_BarMirrorPark { get { return new ContactIcon("char_property_bar_mirror_park"); } }
        public static ContactIcon Property_BarPitchers { get { return new ContactIcon("char_property_bar_pitchers"); } }
        public static ContactIcon Property_BarSingletons { get { return new ContactIcon("char_property_bar_singletons"); } }
        public static ContactIcon Property_BarTequilala { get { return new ContactIcon("char_property_bar_tequilala"); } }
        public static ContactIcon Property_BarUnbranded { get { return new ContactIcon("char_property_bar_unbranded"); } }
        public static ContactIcon Property_CarModShop { get { return new ContactIcon("char_property_car_mod_shop"); } }
        public static ContactIcon Property_CarScrapYard { get { return new ContactIcon("char_property_car_scrap_yard"); } }
        public static ContactIcon Property_CinemaDowntown { get { return new ContactIcon("char_property_cinema_downtown"); } }
        public static ContactIcon Property_CinemaMorningwood { get { return new ContactIcon("char_property_cinema_morningwood"); } }
        public static ContactIcon Property_CinemaVinewood { get { return new ContactIcon("char_property_cinema_vinewood"); } }
        public static ContactIcon Property_GolfClub { get { return new ContactIcon("char_property_golf_club"); } }
        public static ContactIcon Property_PlaneScrapYard { get { return new ContactIcon("char_property_plane_scrap_yard"); } }
        public static ContactIcon Property_SonarCollections { get { return new ContactIcon("char_property_sonar_collections"); } }
        public static ContactIcon Property_TaxiLot { get { return new ContactIcon("char_property_taxi_lot"); } }
        public static ContactIcon Property_TowingImpound { get { return new ContactIcon("char_property_towing_impound"); } }
        public static ContactIcon Property_WeedShop { get { return new ContactIcon("char_property_weed_shop"); } }
        public static ContactIcon Ron { get { return new ContactIcon("char_ron"); } }
        public static ContactIcon Saeeda { get { return new ContactIcon("char_saeeda"); } }
        public static ContactIcon Sasquatch { get { return new ContactIcon("char_sasquatch"); } }
        public static ContactIcon Simeon { get { return new ContactIcon("char_simeon"); } }
        public static ContactIcon SocialClub { get { return new ContactIcon("char_social_club"); } }
        public static ContactIcon Solomon { get { return new ContactIcon("char_solomon"); } }
        public static ContactIcon Steve { get { return new ContactIcon("char_steve"); } }
        public static ContactIcon SteveMichael { get { return new ContactIcon("char_steve_mike_conf"); } }
        public static ContactIcon SteveTrevor { get { return new ContactIcon("char_steve_trev_conf"); } }
        public static ContactIcon Stretch { get { return new ContactIcon("char_stretch"); } }
        public static ContactIcon StripperChastity { get { return new ContactIcon("char_stripper_chastity"); } }
        public static ContactIcon StripperCheetah { get { return new ContactIcon("char_stripper_cheetah"); } }
        public static ContactIcon StripperFufu { get { return new ContactIcon("char_stripper_fufu"); } }
        public static ContactIcon StripperInfernus { get { return new ContactIcon("char_stripper_infernus"); } }
        public static ContactIcon StripperJuliet { get { return new ContactIcon("char_stripper_juliet"); } }
        public static ContactIcon StripperNikki { get { return new ContactIcon("char_stripper_nikki"); } }
        public static ContactIcon StripperPeach { get { return new ContactIcon("char_stripper_peach"); } }
        public static ContactIcon StripperSapphire { get { return new ContactIcon("char_stripper_sapphire"); } }
        public static ContactIcon Tanisha { get { return new ContactIcon("char_tanisha"); } }
        public static ContactIcon Taxi { get { return new ContactIcon("char_taxi"); } }
        public static ContactIcon TaxiLiz { get { return new ContactIcon("char_taxi_liz"); } }
        public static ContactIcon TennisCoach { get { return new ContactIcon("char_tennis_coach"); } }
        public static ContactIcon Tonya { get { return new ContactIcon("char_tow_tonya"); } }
        public static ContactIcon Tracey { get { return new ContactIcon("char_tracey"); } }
        public static ContactIcon Trevor { get { return new ContactIcon("char_trevor"); } }
        public static ContactIcon Wade { get { return new ContactIcon("char_wade"); } }
        public static ContactIcon Youtube { get { return new ContactIcon("char_youtube"); } }
    }
}
